In [2]:
import pandas as pd
import yfinance as yf

In [3]:
ticker = "ORWE.CA"

# Download historical data (daily OHLCV)
df_raw = yf.download(ticker, start="2018-01-01")
df_raw.columns = df_raw.columns.get_level_values(0)

print(df_raw.head())

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open  Volume
Date
2018-01-01  5.323651  5.323651  5.323651  5.323651       0
2018-01-02  5.323651  5.323651  5.323651  5.323651       0
2018-01-03  5.272307  5.333278  5.224173  5.320442  142612
2018-01-04  5.339696  5.419920  5.297980  5.272308  496533
2018-01-07  5.339696  5.339696  5.339696  5.339696       0

In [4]:
df_raw.tail(10)

Price           Close       High        Low       Open   Volume
Date
2026-04-09  22.690001  22.930000  22.549999  22.629999   982093
2026-04-14  22.900000  22.930000  22.549999  22.690001   798114
2026-04-15  22.930000  23.160000  22.860001  22.900000  1246039
2026-04-16  22.799999  23.299999  22.650000  22.930000  1926558
2026-04-19  22.780001  22.980000  22.719999  22.799999   722377
2026-04-20  22.799999  22.879999  22.719999  22.780001   711529
2026-04-21  22.799999  23.000000  22.780001  22.799999   899310
2026-04-22  22.730000  22.950001  22.650000  22.799999  1413911
2026-04-23  22.750000  22.840000  22.600000  22.730000  1671736
2026-04-26  22.770000  23.100000  22.750000  22.750000  1840663

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2048 entries, 2018-01-01 to 2026-04-26
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   2048 non-null   float64
 1   High    2048 non-null   float64
 2   Low     2048 non-null   float64
 3   Open    2048 non-null   float64
 4   Volume  2048 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 96.0 KB

In [6]:
df_raw.to_csv("orwe_data_raw.csv")

# Feature engineering

In [7]:
df = df_raw

In [8]:
#Price based features
df['return_1d'] = df['Close'].pct_change()
df['return_5d'] = df['Close'].pct_change(5)
df['return_10d'] = df['Close'].pct_change(10)

In [9]:
df

Price,Close,High,Low,Open,Volume,return_1d,return_5d,return_10d
Date,,,,,,,,
2018-01-01,5.323651,5.323651,5.323651,5.323651,0,NaN,NaN,NaN
2018-01-02,5.323651,5.323651,5.323651,5.323651,0,0.000000,NaN,NaN
2018-01-03,5.272307,5.333278,5.224173,5.320442,142612,-0.009644,NaN,NaN
2018-01-04,5.339696,5.419920,5.297980,5.272308,496533,0.012782,NaN,NaN
2018-01-07,5.339696,5.339696,5.339696,5.339696,0,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-04-20,22.799999,22.879999,22.719999,22.780001,711529,0.000878,0.004848,0.028417
2026-04-21,22.799999,23.000000,22.780001,22.799999,899310,0.000000,-0.004367,0.017857
2026-04-22,22.730000,22.950001,22.650000,22.799999,1413911,-0.003070,-0.008722,0.006197
2026-04-23,22.750000,22.840000,22.600000,22.730000,1671736,0.000880,-0.002193,0.020179
2026-04-26,22.770000,23.100000,22.750000,22.750000,1840663,0.000879,-0.000439,0.006187

In [10]:
#Trend indicators
df['ma_10'] = df['Close'].rolling(10).mean()
df['ma_50'] = df['Close'].rolling(50).mean()

#Relative postion to trend
df['ma_ratio_10'] = df['Close'] / df['ma_10']
df['ma_ratio_50'] = df['Close'] / df['ma_50']

In [11]:
#RSI indicator
delta = df['Close'].diff()

gain = (delta.where(delta > 0, 0)).rolling(14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(14).mean()

rs = gain / loss
df['rsi'] = 100 - (100 / (1 + rs))

In [12]:
#MACD indicator
ema_12 = df['Close'].ewm(span=12, adjust=False).mean()
ema_26 = df['Close'].ewm(span=26, adjust=False).mean()

df['macd'] = ema_12 - ema_26
df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()
df['macd_hist'] = df['macd'] - df['macd_signal']

In [13]:
#Volatility
df['volatility_10'] = df['Close'].pct_change().rolling(10).std()
df['volatility_20'] = df['Close'].pct_change().rolling(20).std()

In [14]:
#Volume based features
df['volume_avg_10'] = df['Volume'].rolling(10).mean()
df['volume_ratio'] = df['Volume'] / df['volume_avg_10']

In [15]:
df['target'] = (df['Close'].shift(-1) > df['Close']).astype(int)

In [16]:
df.dropna(inplace=True)

In [17]:
#Days with zero volume are holidays so we can remove them
df = df[df['Volume'] != 0]

In [18]:
df

Price,Close,High,Low,Open,Volume,return_1d,return_5d,return_10d,ma_10,ma_50,...,ma_ratio_50,rsi,macd,macd_signal,macd_hist,volatility_10,volatility_20,volume_avg_10,volume_ratio,target
Date,,,,,,,,,,,,,,,,,,,,,
2018-03-11,5.172830,5.262681,5.134323,5.156786,414339,0.003111,0.006871,0.073236,5.107368,5.174242,...,0.999727,58.754901,0.002184,-0.025990,0.028174,0.016413,0.015424,742887.3,0.557741,1
2018-03-12,5.233800,5.307606,5.137531,5.172830,2267233,0.011787,0.030322,0.048875,5.131756,5.172445,...,1.011862,61.594235,0.014021,-0.017988,0.032009,0.013342,0.015179,743148.3,3.050849,0
2018-03-14,5.150368,5.237010,5.073353,5.156786,829527,-0.015941,0.019695,0.000000,5.139778,5.168209,...,0.996548,73.913209,0.023356,-0.003139,0.026496,0.010628,0.015550,526482.4,1.575603,0
2018-03-15,5.079771,5.166412,4.973875,5.150367,1515634,-0.013707,-0.014935,-0.010006,5.134644,5.163011,...,0.983878,66.530686,0.017632,0.001015,0.016617,0.011458,0.015932,641410.4,2.362971,0
2018-03-18,5.002756,5.086188,4.957830,5.079770,726843,-0.015161,-0.032878,-0.026234,5.121166,5.156272,...,0.970227,50.925942,0.006803,0.002172,0.004630,0.012256,0.016137,703304.2,1.033469,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-20,22.799999,22.879999,22.719999,22.780001,711529,0.000878,0.004848,0.028417,22.682000,22.722400,...,1.003415,69.999981,0.070793,0.003108,0.067685,0.008239,0.009012,869319.1,0.818490,0
2026-04-21,22.799999,23.000000,22.780001,22.799999,899310,0.000000,-0.004367,0.017857,22.722000,22.716400,...,1.003680,71.428585,0.076974,0.017881,0.059093,0.007828,0.008905,909518.2,0.988776,0
2026-04-22,22.730000,22.950001,22.650000,22.799999,1413911,-0.003070,-0.008722,0.006197,22.736000,22.706000,...,1.001057,69.306896,0.075355,0.029376,0.045979,0.007580,0.008948,1005267.6,1.406502,1
2026-04-23,22.750000,22.840000,22.600000,22.730000,1671736,0.000880,-0.002193,0.020179,22.781000,22.694200,...,1.002459,63.742662,0.074824,0.038466,0.036358,0.005932,0.008821,1123747.4,1.487644,1
2026-04-26,22.770000,23.100000,22.750000,22.750000,1840663,0.000879,-0.000439,0.006187,22.795000,22.681200,...,1.003915,68.518521,0.075150,0.045803,0.029348,0.003875,0.008733,1221233.0,1.507217,0

In [19]:
df.to_csv("orwe_data_features.csv")

In [20]:
df.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'return_1d', 'return_5d',
       'return_10d', 'ma_10', 'ma_50', 'ma_ratio_10', 'ma_ratio_50', 'rsi',
       'macd', 'macd_signal', 'macd_hist', 'volatility_10', 'volatility_20',
       'volume_avg_10', 'volume_ratio', 'target'],
      dtype='object', name='Price')